### ISSUE TITLE
大佬。我同一个直播流，ijk获取时长为0，exo就是每个切片的长度

### ISSUE THREAD

**Issue by xuzh2017** [Jzvd/JiaoZiVideoPlayer#113]
我想根据时长判断是直播还是点播，有什么好办法吗

**Comment by lipangit** [comment]
这个有点新颖



---原始邮件---
发件人: "xuzh2017"<notifications@github.com&gt;
发送时间: 2020年4月15日(周三) 下午3:42
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 大佬。我同一个直播流，ijk获取时长为0，exo就是每个切片的长度 (#113)




 
我想根据时长判断是直播还是点播，有什么好办法吗

**Comment by xuzh2017** [comment]
> 这个有点新颖
> […](#)
> ---原始邮件--- 发件人: "xuzh2017"<notifications@github.com&gt; 发送时间: 2020年4月15日(周三) 下午3:42 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 大佬。我同一个直播流，ijk获取时长为0，exo就是每个切片的长度 (#113) 我想根据时长判断是直播还是点播，有什么好办法吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

判断直播还是点播有什么其他办法吗大佬

**Comment by lipangit** [comment]
首先播放之前就要知道它是不是直播，通过其他方式判断的结果都不扎实。比如小于某个时间可以认定为直播。



---原始邮件---
发件人: "xuzh2017"<notifications@github.com&gt;
发送时间: 2020年4月16日(周四) 上午10:16
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 大佬。我同一个直播流，ijk获取时长为0，exo就是每个切片的长度 (#113)




  
这个有点新颖
 …
 ---原始邮件--- 发件人: "xuzh2017"<notifications@github.com&gt; 发送时间: 2020年4月15日(周三) 下午3:42 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 大佬。我同一个直播流，ijk获取时长为0，exo就是每个切片的长度 (#113) 我想根据时长判断是直播还是点播，有什么好办法吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
判断直播还是点播有什么其他办法吗大佬

**Comment by xuzh2017** [comment]
> 首先播放之前就要知道它是不是直播，通过其他方式判断的结果都不扎实。比如小于某个时间可以认定为直播。
> […](#)
> ---原始邮件--- 发件人: "xuzh2017"<notifications@github.com&gt; 发送时间: 2020年4月16日(周四) 上午10:16 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [Jzvd/JiaoZiVideoPlayer] 大佬。我同一个直播流，ijk获取时长为0，exo就是每个切片的长度 (#113) 这个有点新颖 … ---原始邮件--- 发件人: "xuzh2017"<notifications@github.com&gt; 发送时间: 2020年4月15日(周三) 下午3:42 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 大佬。我同一个直播流，ijk获取时长为0，exo就是每个切片的长度 (#113) 我想根据时长判断是直播还是点播，有什么好办法吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 判断直播还是点播有什么其他办法吗大佬 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

只好如此了，谢谢
