### ISSUE TITLE
怎么开始播放的时候 就根据视频的宽高，竖屏播放还是横屏播放

### ISSUE THREAD

**Issue by bingdu0** [Jzvd/JiaoZiVideoPlayer#356]
播放的时候要点 全屏按钮才会执行onVideoSizeChanged   计算宽高来切换横屏还是竖屏 。我现在想让开始按钮播放就直接横屏还是竖屏。不想点那个全屏按钮。

**Comment by lipangit** [comment]
继承jzvdstd 复写
onVideoSizeChanged函数，可以取得高宽，判断之后进入横屏或者竖屏。

这个函数在第一次开始播放的时候就会调用，和全屏没关系

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月22日(周六) 晚上9:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jzvd/JZVideo] 怎么开始播放的时候 就根据视频的宽高，竖屏播放还是横屏播放 (#356)




 
播放的时候要点 全屏按钮才会执行onVideoSizeChanged   计算宽高来切换横屏还是竖屏 。我现在想让开始按钮播放就直接横屏还是竖屏。不想点那个全屏按钮。

**Comment by bingdu0** [comment]
> 继承jzvdstd 复写 onVideoSizeChanged函数，可以取得高宽，判断之后进入横屏或者竖屏。 这个函数在第一次开始播放的时候就会调用，和全屏没关系
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年5月22日(周六) 晚上9:17 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Jzvd/JZVideo] 怎么开始播放的时候 就根据视频的宽高，竖屏播放还是横屏播放 (#356) 播放的时候要点 全屏按钮才会执行onVideoSizeChanged 计算宽高来切换横屏还是竖屏 。我现在想让开始按钮播放就直接横屏还是竖屏。不想点那个全屏按钮。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我那个意思是 ，demo里面这个 JzvdStdAutoOrizental    ，onVideoSizeChanged  会执行 ，这段代码
`  @Override
    public void onVideoSizeChanged(int width, int height) {
        super.onVideoSizeChanged(width, height);
        if (width > 0 && height > 0) {
            if (height > width) {
                Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
            } else {
                Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
            }
        }
    }`

如果宽大于高应该是横屏  ，但是activity并没有横屏。只有点了全屏按钮之后才可以切换横竖屏。

**Comment by lipangit** [comment]
是这个代码设置，然后调用jzutil里面有一个request什么的函数，去执行这两个设置。都是全局函数，随时调用随时生效



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月23日(周日) 上午9:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jzvd/JZVideo] 怎么开始播放的时候 就根据视频的宽高，竖屏播放还是横屏播放 (#356)




  
继承jzvdstd 复写 onVideoSizeChanged函数，可以取得高宽，判断之后进入横屏或者竖屏。 这个函数在第一次开始播放的时候就会调用，和全屏没关系
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年5月22日(周六) 晚上9:17 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [Jzvd/JZVideo] 怎么开始播放的时候 就根据视频的宽高，竖屏播放还是横屏播放 (#356) 播放的时候要点 全屏按钮才会执行onVideoSizeChanged 计算宽高来切换横屏还是竖屏 。我现在想让开始按钮播放就直接横屏还是竖屏。不想点那个全屏按钮。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我那个意思是 ，demo里面这个 JzvdStdAutoOrizental    ，onVideoSizeChanged  会执行 ，这段代码
   @Override public void onVideoSizeChanged(int width, int height) { super.onVideoSizeChanged(width, height); if (width &gt; 0 &amp;&amp; height &gt; 0) { if (height &gt; width) { Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT; } else { Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE; } } }
 
如果宽大于高应该是横屏  ，但是activity并没有横屏。只有点了全屏按钮之后才可以切换横竖屏。
