### ISSUE TITLE
请问这个库支持 rtmp播放吗?

### ISSUE THREAD

**Issue by roybill** [Jzvd/JiaoZiVideoPlayer#415]

**Comment by lipangit** [comment]
饺子是做ui的。先研究哪个播放内核能播放你的url，然后看饺子的哪个ui需求，参考mediaplayerinterface，把播放内核植入到ui里面。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月2日(周四) 晚上6:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jzvd/JZVideo] 请问这个库支持 rtmp播放吗? (Issue #415)




 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by roybill** [comment]
jzvdStd.setUp(url, "饺子闭眼睛",JzvdStd.SCREEN_NORMAL,JZMediaIjk.class);//这样可以
谢谢,修改播放内核,确实可以. 但是左右有很大的黑边,这种有办法去掉吗?
